Categories = {
    1: "Main Weapon",
    5: "Sub-Weapon",
    10: "Awakening",
    15: "Armor",
    20: "Accessories",
    25: "Material",
    30: "Enchantment/Upgrade",
    35: "Consumables",
    40: "Life Tools",
    45: "Alchemy Stone",
    50: "Magic Crystal",
    55: "Pearl Item",
    60: "Dye",
    65: "Mount",
    70: "Ship",
    75: "Wagon",
    80: "Furniture"
}

Links = {
    "MarketList": "https://marketweb-eu.blackdesertonline.com/Home/GetWorldMarketList",
    "SubList": "https://marketweb-eu.blackdesertonline.com/Home/GetWorldMarketSubList",
    "SellBuyInfo": "https://marketweb-eu.blackdesertonline.com/Home/GetItemSellBuyInfo",
    "RecipeSite": "https://bddatabase.net/us/recipe/"
}

Enchantments = {
    0: "No Enchantment",
    1: "+1",
    2: "+2",
    3: "+3",
    4: "+4",
    5: "+5",
    6: "+6",
    7: "+7",
    8: "+8",
    9: "+9",
    10: "+10",
    11: "+11",
    12: "+12",
    13: "+13",
    14: "+14",
    15: "+15",
    16: "PRI",
    17: "DUO",
    18: "TRI",
    19: "TET",
    20: "PEN"
}

SubCategories = {
    "Main Weapon": {
        1: "Longsword",
        2: "Longbow",
        3: "Amulet",
        4: "Axe",
        5: "Shortsword",
        6: "Blade",
        7: "Staff",
        8: "Kriegsmesser",
        9: "Gauntlet",
        10: "Crescent Pendulum",
        11: "Crossbow",
        12: "Florang",
        13: "Battle Axe"
    },
    "Sub-Weapon": {
        1: "Shield",
        2: "Dagger",
        3: "Talisman",
        4: "Ornamental Knot",
        5: "Trinket",
        6: "Horn Bow",
        7: "Kunai",
        8: "Shuriken",
        9: "Vambrace",
        10: "Noble Sword",
        11: "Ra&#39;ghon",
        12: "Vitclari"
    },
    "Awakening": {
        1: "Great Sword",
        2: "Scythe",
        3: "Iron Buster",
        4: "Kamasylven Sword",
        5: "Celestial Bo Staff",
        6: "Lancia",
        7: "Crescent Blade",
        8: "Kerispear",
        9: "Sura Katana",
        10: "Sah Chakram",
        11: "Aad Sphera",
        12: "Godr Sphera",
        13: "Vediant",
        14: "Gardbrace",
        15: "Cestus",
        16: "Crimson Glaives",
        17: "Greatbow",
        19: "Jordun"
    },
    "Armor": {
        1: "Helmet",
        2: "Armor",
        3: "Gloves",
        4: "Shoes",
        5: "Functional Clothes",
        6: "Crafted Clothes"
    },
    "Accessories": {
        1: "Ring",
        2: "Necklace",
        3: "Earring",
        4: "Belt"
    },
    "Material": {
        1: "Ore/Gem",
        2: "Plants",
        3: "Seed/Fruit",
        4: "Leather",
        5: "Blood",
        6: "Meat",
        7: "Seafood",
        8: "Misc."
    },
    "Enchantment/Upgrade": {
        1: "Black Stone",
        2: "Upgrade"
    },
    "Consumables": {
        1: "Offensive Elixir",
        2: "Defensive Elixir",
        3: "Functional Elixir",
        4: "Food",
        5: "Potion",
        6: "Siege Items",
        7: "Item Parts",
        8: "Other Consumables"
    },
    "Life Tools": {
        1: "Lumbering Axe",
        2: "Fluid Collector",
        3: "Butcher Knife",
        4: "Pickaxe",
        5: "Hoe",
        6: "Tanning Knife",
        7: "Fishing Tools",
        8: "Matchlock",
        9: "Alchemy/Cooking",
        10: "Other Tools"
    },
    "Alchemy Stone": {
        1: "Destruction",
        2: "Protection",
        3: "Life",
        4: "Spirit Stone"
    },
    "Magic Crystal": {
        1: "Main Weapon",
        2: "Sub-weapon",
        3: "Helmet",
        4: "Armor",
        5: "Gloves",
        6: "Shoes",
        7: "Versatile"
    },
    "Pearl Item": {
        1: "Male Apparel (Set)",
        2: "Female Apparels (Set)",
        3: "Male Apparel (Individual)",
        4: "Female Apparel (Individual)",
        5: "Class-based Apparel (Set)",
        6: "Functional",
        7: "Mount",
        8: "Pet"
    },
    "Dye": {
        1: "Basic",
        2: "Olvia",
        3: "Velia",
        4: "Heidelian",
        5: "Keplan",
        6: "Calpheon",
        7: "Mediah",
        8: "Valencia"
    },
    "Mount": {
        1: "Registration",
        2: "Feed",
        3: "Champron",
        4: "Barding",
        5: "Saddle",
        6: "Stirrups",
        7: "Horseshoe",
        9: "[Elephant] Stirrups",
        10: "[Elephant] Armor",
        11: "[Elephant] Mask",
        12: "[Elephant] Saddle",
        13: "Courser Training"
    },
    "Ship": {
        1: "Registration",
        2: "Cargo",
        3: "Prow",
        4: "Decoration",
        5: "Totem",
        6: "Prow Statue",
        7: "Plating",
        8: "Cannon",
        9: "Sail"
    },
    "Wagon": {
        1: "Registration",
        2: "Wheel",
        3: "Cover",
        4: "Flag",
        5: "Emblem",
        6: "Lamp"
    },
    "Furniture": {
        1: "Bed",
        2: "Bedside Table/Table",
        3: "Wardrobe/Bookshelf",
        4: "Sofa/Chair",
        5: "Chandelier",
        6: "Floor/Carpet",
        7: "Wall/Curtain",
        8: "Decoration",
        9: "Others"
    }
}

MaterialGroups = {
    "Cereals": [
        "Wheat",
        "Barley",
        "Potato",
        "Sweet Potato",
        "Corn"
    ],
    "Dough": [
        "Wheat Dough",
        "Barley Dough",
        "Potato Dough",
        "Sweet Potato Dough",
        "Corn Dough"
    ],
    "Fruits": [
        "Strawberry",
        "Grape",
        "Apple",
        "Cherry",
        "Pear",
        "Banana",
        "Pineapple"
    ],
    "Meat": [
        "Deer Meat",
        "Fox Meat",
        "Rhino Meat",
        "Pork",
        "Beef",
        "Raccoon Meat",
        "Weasel Meat",
        "Bear Meat",
        "Wolf Meat",
    ],
    "Flour": [
        "Wheat Flour",
        "Barley Flour",
        "Potato Flour",
        "Sweet Potato Flour",
        "Corn Flour"
    ],
    "Fish": [
        "Mudskipper",
        "Tuna",
        "Beltfish",
        "Flounder",
        "Salmon",
        "Amberjack",
        "Porgy",
        "Swellfish",
        "Saurel",
        "Rockfish",
        "Carp",
        "Crucian Carp",
        "Trout",
        "Catfish",
        "Freshwater Eel",
        "Snakehead",
        "Cherry Salmon",
        "Cuvier",
        "Sunfish",
        "Sea Bass",
        "Angler",
        "Swordfish",
        "Mackerel",
        "Flying Fish",
        "Skipjack",
        "Ray",
        "Filefish",
        "Scorpion Fish",
        "Mullet",
        "Swiri",
        "Sturgeon",
        "Piranha",
        "Mandarin Fish",
        "Lenok",
        "Arowana",
        "Sweetfish",
        "Bass",
        "Dace",
        "Bluegill",
        "Perch",
        "Notch Jaw",
        "Mudfish",
        "Goby Minnow",
        "Bitterling",
        "Bleeker",
        "Yellowfin Sculpin",
        "Cero",
        "Sea Eel",
        "Croaker",
        "Greenling",
        "Flatfish",
        "Grunt",
        "Herring",
        "Sardine",
        "Round Herring",
        "Silver-Stripe Round Herring",
        "Whiting",
        "Dolphinfish",
        "Striped Catfish",
        "Gunnel",
        "Golden-Thread",
        "Nibbler",
        "Siganid",
        "Bluefish",
        "Surfperch",
        "Blackfin Sweeper",
        "Smokey Chromis",
        "Maomao",
        "Pintado",
        "Gurnard",
        "John Dory",
        "Sandfish",
        "Rosefish",
        "Grouper",
        "Bigeye",
        "Fourfinger Threadfin",
        "Leather Carp",
        "Striped Shiner",
        "Barbel Steed",
        "Soho Bitterling",
        "Bubble Eye",
        "Pacu",
        "Yellow-Head Catfish",
        "Smelt",
        "Rosy Bitterling",
        "Roundtail Paradisefish",
        "Grayling",
        "Tapertail Anchovy",
        "Kuhlia Marginata",
        "Rock Hind",
        "Butterflyfish",
        "Clownfish",
        "Blue Tang",
        "Checkerboard Wrasse",
        "Pomfret",
        "White Shark",
        "Blue Shark",
        "Hammerhead",
        "Galeocerdo Cuvier",
        "Whale Shark",
        "Saw Shark",
        "Minke Whale",
        "Humpback Whale",
        "Killer Whale",
        "Hammer Whale",
        "Narwhale",
        "Beluga Whale",
        "Bottlenose Dolphin",
        "Mackereltuna",
        "Bigeye Tuna",
        "Yellowfin Tuna",
        "Albacore",
        "Bluefin Tuna",
        "Yellow Swordfish",
        "Marlin",
        "Sailfish",
        "Black Marlin",
        "Giant Grouper",
        "Moray",
        "Tilefish",
        "Porcupine Fish",
        "Tongue Sole",
        "Atka Mackerel",
        "Mackerel Pike",
        "Horn Fish",
        "Dollarfish",
        "Sandeel",
        "Sperm Whale"
    ],
    "Dried Fish": [
        "Dried Mudskipper",
        "Dried Tuna",
        "Dried Beltfish",
        "Dried Flounder",
        "Dried Salmon",
        "Dried Amberjack",
        "Dried Porgy",
        "Dried Swellfish",
        "Dried Saurel",
        "Dried Rockfish",
        "Dried Carp",
        "Dried Crucian Carp",
        "Dried Trout",
        "Dried Catfish",
        "Dried Freshwater Eel",
        "Dried Snakehead",
        "Dried Cherry Salmon",
        "Dried Cuvier",
        "Dried Sunfish",
        "Dried Sea Bass",
        "Dried Angler",
        "Dried Swordfish",
        "Dried Mackerel",
        "Dried Flying Fish",
        "Dried Skipjack",
        "Dried Ray",
        "Dried Filefish",
        "Dried Scorpion Fish",
        "Dried Mullet",
        "Dried Swiri",
        "Dried Sturgeon",
        "Dried Piranha",
        "Dried Mandarin Fish",
        "Dried Lenok",
        "Dried Arowana",
        "Dried Sweetfish",
        "Dried Bass",
        "Dried Dace",
        "Dried Bluegill",
        "Dried Perch",
        "Dried Notch Jaw",
        "Dried Mudfish",
        "Dried Goby Minnow",
        "Dried Bitterling",
        "Dried Bleeker",
        "Dried Yellowfin Sculpin",
        "Dried Cero",
        "Dried Sea Eel",
        "Dried Croaker",
        "Dried Greenling",
        "Dried Flatfish",
        "Dried Grunt",
        "Dried Herring",
        "Dried Sardine",
        "Dried Round Herring",
        "Dried Silver-Stripe Round Herring",
        "Dried Whiting",
        "Dried Dolphinfish",
        "Dried Striped Catfish",
        "Dried Gunnel",
        "Dried Golden-Thread",
        "Dried Nibbler",
        "Dried Siganid",
        "Dried Bluefish",
        "Dried Surfperch",
        "Dried Blackfin Sweeper",
        "Dried Smokey Chromis",
        "Dried Maomao",
        "Dried Pintado",
        "Dried Gurnard",
        "Dried John Dory",
        "Dried Sandfish",
        "Dried Rosefish",
        "Dried Grouper",
        "Dried Bigeye",
        "Dried Fourfinger Threadfin",
        "Dried Leather Carp",
        "Dried Striped Shiner",
        "Dried Barbel Steed",
        "Dried Soho Bitterling",
        "Dried Bubble Eye",
        "Dried Pacu",
        "Dried Yellow-Head Catfish",
        "Dried Smelt",
        "Dried Rosy Bitterling",
        "Dried Roundtail Paradisefish",
        "Dried Grayling",
        "Dried Tapertail Anchovy",
        "Dried Kuhlia Marginata",
        "Dried Rock Hind",
        "Dried Butterflyfish",
        "Dried Clownfish",
        "Dried Blue Tang",
        "Dried Checkerboard Wrasse",
        "Dried Pomfret",
        "Dried White Shark",
        "Dried Blue Shark",
        "Dried Hammerhead",
        "Dried Galeocerdo Cuvier",
        "Dried Whale Shark",
        "Dried Saw Shark",
        "Dried Minke Whale",
        "Dried Humpback Whale",
        "Dried Killer Whale",
        "Dried Hammer Whale",
        "Dried Narwhale",
        "Dried Beluga Whale",
        "Dried Bottlenose Dolphin",
        "Dried Mackereltuna",
        "Dried Bigeye Tuna",
        "Dried Yellowfin Tuna",
        "Dried Albacore",
        "Dried Bluefin Tuna",
        "Dried Yellow Swordfish",
        "Dried Marlin",
        "Dried Sailfish",
        "Dried Black Marlin",
        "Dried Giant Grouper",
        "Dried Moray",
        "Dried Tilefish",
        "Dried Porcupine Fish",
        "Dried Tongue Sole",
        "Dried Atka Mackerel",
        "Dried Mackerel Pike",
        "Dried Horn Fish",
        "Dried Dollarfish",
        "Dried Sandeel",
        "Dried Sperm Whale"
    ],
    "Bird Meat": [
        "Kuku Bird Meat",
        "Flamingo Meat",
        "Chicken Meat"
    ],
    "Plants": [
        "Sunflower",
        "Rose",
        "Tulip"
    ],
    "Seafood": [
        "Cuttlefish",
        "Squid",
        "Terrapin",
        "Jellyfish",
        "Crawfish",
        "Crab",
        "Octopus",
        "Starfish",
        "Shellfish",
        "Seahorse"
    ],
    "Reptile Meat": [
        "Lizard Meat",
        "Worm Meat",
        "Waragon Meat",
        "Cheetah Dragon Meat"
    ],
    "Vegetables": [
        "Tomato",
        "Paprika",
        "Pumpkin",
        "Cabbage",
        "Olive"
    ],
    "Gemstones": [
        "Magic Crystal of Crimson Flame - Precision",
        "Magic Crystal of Crimson Flame - Power",
        "Magic Crystal of Crimson Flame - Carnage",
        "Magic Crystal of Crimson Flame - Carnage",
        "Magic Crystal of Crimson Flame - Carnage",
        "Magic Crystal of Abundance - Armor",
        "Magic Crystal of Abundance - Vigor",
        "Magic Crystal of Abundance - Patience",
        "Magic Crystal of Abundance - Healing",
        "Magic Crystal of Abundance - Resonance",
        "Magic Crystal of Nature - Swiftness",
        "Magic Crystal of Nature - Adamantine",
        "Magic Crystal of Nature - Ascension",
        "Magic Crystal of the Sun - Assault",
        "Magic Crystal of the Sun - Sturdiness",
        "Magic Crystal of the Sun - Valor",
        "Magic Crystal of Enchantment - Memory",
        "Magic Crystal of Enchantment - Intimidation",
        "Magic Crystal of Enchantment - Vision",
        "Magic Crystal of Enchantment - Agility"
    ],
    "Blood 1": {
        "Wolf Blood",
        "Flamingo Blood",
        "Rhino Blood",
        "Cheetah Dragon Blood"
    },
    "Blood 2": {
        "Deer Blood",
        "Sheep Blood",
        "Pig Blood",
        "Waragon Blood",
        "Ox Blood"
    },
    "Blood 3": {
        "Weasel Blood",
        "Fox Blood",
        "Raccoon Blood"
    },
    "Blood 4": {
        "Troll Blood",
        "Beer Blood",
        "Ogre Blood",
        "Dinosaur Blood"
    },
    "Blood 5": {
        "Worm Blood",
        "Lizard Blood",
        "Bat Blood",
        "Kuku Bird Blood",
        "Cobra Blood"
    },
}
